### ISSUE TITLE
Mean is completely wrong in one benchmark (wrong rounding)??

### ISSUE THREAD

**Issue by Kha** [parttimenerd/temci#43]
```
$ temci report --reporter console bench/binarytrees.lean.bench                    
binarytrees.lean.out (   19 single benchmarks)
	 [average resident set (not swapped out) size in K] mean =          0.0(0), deviation =   0.0
	 [average total mem usage (in K)] mean =          0.0(0), deviation =   0.0
	 [elapsed real (wall clock) time (in seconds)] mean =          2.(00), deviation = 4.70804%
	 [maximum resident set (not swapped out) size in K] mean =   180(835).(79), deviation = 0.09277%
	 [system (kernel) CPU time used (in seconds)] mean =          0.0(5), deviation = 17.31718%
	 [user CPU time used (in seconds)] mean =          7.(26), deviation = 2.51927%
$ cat bench/binarytrees.lean.bench
- attributes: {description: binarytrees.lean.out}
  data:
    __ov-time: [3.0890724658966064, 2.944934368133545, 2.964219570159912, 2.605692148208618,
      2.976245880126953, 2.9942073822021484, 2.9550039768218994, 3.0588197708129883,
      3.017014741897583, 2.985790967941284, 2.9475955963134766, 2.989563226699829,
      3.2769174575805664, 3.0084168910980225, 2.991102457046509, 2.9708974361419678,
      3.3510773181915283, 3.036498546600342, 2.960247755050659]
    avg_mem_usage: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    avg_res_set: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    etime: [3.08, 2.93, 2.95, 2.6, 2.97, 2.98, 2.95, 3.05, 3.01, 2.98, 2.94, 2.98,
      3.27, 3.0, 2.98, 2.96, 3.34, 3.03, 2.95]
    max_res_set: [180444.0, 181024.0, 180860.0, 180964.0, 180828.0, 180892.0, 180892.0,
      180960.0, 180828.0, 180832.0, 180904.0, 180500.0, 180868.0, 180896.0, 181028.0,
      180792.0, 181032.0, 180508.0, 180828.0]
    stime: [0.07, 0.03, 0.05, 0.05, 0.06, 0.06, 0.05, 0.06, 0.06, 0.04, 0.05, 0.06,
      0.05, 0.07, 0.05, 0.05, 0.05, 0.06, 0.05]
    utime: [7.11, 7.34, 7.25, 6.56, 7.32, 7.25, 7.37, 7.34, 7.46, 7.31, 7.3, 7.26,
      7.22, 7.35, 7.38, 7.36, 7.15, 7.28, 7.32]
- property_descriptions: {avg_mem_usage: average total mem usage (in K), avg_res_set: average
      resident set (not swapped out) size in K, etime: elapsed real (wall clock) time
      (in seconds), max_res_set: maximum resident set (not swapped out) size in K,
    stime: system (kernel) CPU time used (in seconds), utime: user CPU time used (in
      seconds)}
```

**Comment by parttimenerd** [comment]
I cannot reproduce your error. Could you please state your used `temci.yaml`?

**Comment by Kha** [comment]
Reproduced on current master
```

# Logging level
log_level: info

# Additional settings file
settings_file: ''

# Acquire sudo privileges and run benchmark programs with non-sudo user. Only supported on the command line.
sudo: false

# Used temporary directory
tmp_dir: /tmp/temci

build:
    
    # Input file with the program blocks to build
    in: build.yaml
    
    # Resulting run config file
    out: run.exec.yaml
    
    # Number of threads that build simultaneously
    threads: 1
    
    # Assembly randomization
    rand:
        
        # Randomize the bss sub segments?
        bss: false
        
        # Randomize the data sub segments?
        data: false
        
        # Randomize the file structure.
        file_structure: false
        
        # 0: don't randomize, > 0 randomize with paddings in range(0, x)
        heap: 0
        
        # Randomize the linking order
        linker: false
        
        # Randomize the rodata sub segments?
        rodata: false
        
        # Used gnu assembler, default is /usr/bin/as
        used_as: /usr/bin/as
        
        # Used gnu linker, default is /usr/bin/ld
        used_ld: /usr/bin/ld

# Environment variables for the benchmarked programs, includes the user used for generated files
env:
    
    PATH: /nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/bin:/nix/store/16p27xpsh35wp1mqaj090w7h3zpc0h87-temci-local/bin:/nix/store/bn8xa5ww2p9pghjdgcix3w0alwlm00wh-python3.7-setuptools-40.8.0/bin:/nix/store/pgna96izm3jif088rzim419nn136r7a5-python3.7-humanfriendly-4.18/bin:/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/bin:/nix/store/wln4anp2a4axq8iapqib3wbk6qsh0yjr-python3.7-coverage-4.5.2/bin:/nix/store/1jb598q3mmj18354gs38p4bqbqvfgsf5-python3.7-cpuset-py3-1.0/bin:/nix/store/xbp51gqhxck78rzlyaj80yvhk2k0y7gl-python3.7-xlrd-1.2.0/bin:/nix/store/9nr771jg64xnhav2fyqpvax75md9m9jk-python3.7-odfpy-1.4.0/bin:/nix/store/i7vrd6sa32jji4brc5rbck2g2r765gdp-python3.7-numpy-1.16.1/bin:/nix/store/d8bnldkwm4pdbmcbj0lh5b7f9s32zi3b-python3.7-tables-3.4.4/bin:/nix/store/g6cl3pd221abfwhzlq960lc7wi0is97n-freetype-2.9.1-dev/bin:/nix/store/q6821d46lc5514rfh537c20f9ay2760l-bzip2-1.0.6.0.1-bin/bin:/nix/store/142xnc8slrfq6vz38vnadwqrfq9khbv6-libpng-apng-1.6.36-dev/bin:/nix/store/dzn2ljyj6nnqmyjrsmi5v9msbh725kg2-python3.7-pbr-5.1.2/bin:/nix/store/mcyvp1s45scjkkhyb1m16aqlsb8wr6hs-bash-interactive-4.4-p23/bin:/nix/store/j7zh0n0h3ifzjq4fch713z9fkwp57mf9-patchelf-0.9/bin:/nix/store/sy6cxd224k9mk64n0xx70ar2vfjin6wv-gcc-wrapper-7.4.0/bin:/nix/store/348bgpalbgx8kyg6bqr24f45dzqhp9pf-gcc-7.4.0/bin:/nix/store/jjmx92bryk0q9wsqmf2fbaaqsm5qdjys-glibc-2.27-bin/bin:/nix/store/fxvgwfb8f450aqq2xdbzy6jxvymcwvn3-coreutils-8.31/bin:/nix/store/3g4bgh46msclfldnyl9pqxfsp8980z89-binutils-wrapper-2.31.1/bin:/nix/store/6k95q6vvnmspf3c0nm8q55sixsvmn9nc-binutils-2.31.1/bin:/nix/store/dqw25rb23i4j19g87l90gfb8fshy75yc-python3-3.7.3-env/bin:/nix/store/16p27xpsh35wp1mqaj090w7h3zpc0h87-temci-local/bin:/nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/bin:/nix/store/bn8xa5ww2p9pghjdgcix3w0alwlm00wh-python3.7-setuptools-40.8.0/bin:/nix/store/pgna96izm3jif088rzim419nn136r7a5-python3.7-humanfriendly-4.18/bin:/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/bin:/nix/store/wln4anp2a4axq8iapqib3wbk6qsh0yjr-python3.7-coverage-4.5.2/bin:/nix/store/1jb598q3mmj18354gs38p4bqbqvfgsf5-python3.7-cpuset-py3-1.0/bin:/nix/store/xbp51gqhxck78rzlyaj80yvhk2k0y7gl-python3.7-xlrd-1.2.0/bin:/nix/store/9nr771jg64xnhav2fyqpvax75md9m9jk-python3.7-odfpy-1.4.0/bin:/nix/store/i7vrd6sa32jji4brc5rbck2g2r765gdp-python3.7-numpy-1.16.1/bin:/nix/store/d8bnldkwm4pdbmcbj0lh5b7f9s32zi3b-python3.7-tables-3.4.4/bin:/nix/store/g6cl3pd221abfwhzlq960lc7wi0is97n-freetype-2.9.1-dev/bin:/nix/store/q6821d46lc5514rfh537c20f9ay2760l-bzip2-1.0.6.0.1-bin/bin:/nix/store/142xnc8slrfq6vz38vnadwqrfq9khbv6-libpng-apng-1.6.36-dev/bin:/nix/store/dzn2ljyj6nnqmyjrsmi5v9msbh725kg2-python3.7-pbr-5.1.2/bin:/nix/store/i4vd5niwzial0anm2k9cld4n2k8xp3yn-perf-linux-4.19.40/bin:/nix/store/b6x2ws5prlw6mi8iav73lmg74x5r5zfk-time-1.9/bin:/nix/store/y9vc7brvva3rsdx6llr9y86nsf9wv4j5-findutils-4.6.0/bin:/nix/store/y8yyi8m65qpw8g8iqswhsnfmi4rjmkj3-diffutils-3.7/bin:/nix/store/gzxhlpdq85mpgh1ac0yynyd51kkj0j9m-gnused-4.7/bin:/nix/store/x5wp3m2674h75gzknrx9fyj2f370r3p1-gnugrep-3.3/bin:/nix/store/m9i7j3cwsrlz637db8mgk7k811qlnyga-gawk-4.2.1/bin:/nix/store/lqdgxavfilyjn8mskv9q2k17d7hbminv-gnutar-1.32/bin:/nix/store/c9w21ljdfkd7cd6r9079jbbhvrl7mz9r-gzip-1.10/bin:/nix/store/isa7p7avp5xsyrdmv07vpczj75v402vw-bzip2-1.0.6.0.1-bin/bin:/nix/store/0b0a754s44vb6vp2hpi6ff9gy90a72l5-gnumake-4.2.1/bin:/nix/store/5p8qcz6i13ymgf80kimhx2g9pb5r5nia-bash-4.4-p23/bin:/nix/store/3szsgjdy10vyhjb42hgwc5nkpaqa0c0x-patch-2.7.6/bin:/nix/store/622padp2k9nfpx35hl3az32vq6vg4pwh-xz-5.2.4-bin/bin:/home/sebastian/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    
    USER: sebastian

package:
    
    # Only log proposed actions?
    dry_run: false
    
    # Name of the produced file to reverse the actions of a package.
    reverse_file: reverse.temci
    
    # If not empty, recipient of a mail if an error occurs or a command finished.
    send_mail: ''
    
    actions:
        
        # Default sleep seconds for the sleep action.
        sleep: 30
    
    compression:
        
        # Compression level. 0 = low, -9 high compression.
        level: -6
        
        # The used compress program. The parallel version (pixz or pigz) is used if available.
        program: xz

report:
    
    # Exclude all data sets that contain only NaNs.
    exclude_invalid: true
    
    # Properties that aren't shown in the report.
    excluded_properties: [__ov-time]
    
    # File that contains the benchmarking results
    in: run_output.yaml
    
    # Replace the property names in reports with longer more descriptive versions?
    long_properties: true
    
    # Possible reporter are 'console', 'html', 'html2' and 'csv'
    reporter: html2
    
    # Produce xkcd like plots (requires the humor sans font to be installed)
    xkcd_like_plots: false
    
    #   Simple reporter that outputs just text.
    console_misc:
        
        # Output file name or stdard out (-)
        out: '-'
        
        # Print statistical tests for every property for every two programs
        with_tester_results: true
    
    #   Simple reporter that outputs just a configurable csv table with rows for each run block
    csv_misc:
        
        # List of valid column specs, format is a comma separated list of 'PROPERTY\[mod\]' or 'ATTRIBUTE' mod is one of: mean, stddev, property, min, max and stddev per mean, optionally a formatting option can be given viaPROPERTY\[mod|OPT1OPT2…\], where the OPTs are one of the following: % (format as percentage), p (wrap insignificant digits in parentheses (+- 2 std dev)), s (use scientific notation, configured in report/number) and o (wrap digits in the order of magnitude of 2 std devs in parentheses). PROPERTY can be either the description or the short version of the property. Configure the number formatting further via the number settings in the settings file
        columns: [description]
        
        # Output file name or standard out (-)
        out: '-'
    
    #   Reporter that produces a HTML based report with lot's of graphics.
    #   A rewrite of the original HTMLReporter
    html2_misc:
        
        # Alpha value for confidence intervals
        alpha: 0.05
        
        # Height per run block for the big comparison box plots
        boxplot_height: 2.0
        
        # Width of all big plotted figures
        fig_width_big: 25.0
        
        # Width of all small plotted figures
        fig_width_small: 15.0
        
        # Format string used to format floats
        float_format: '{:5.2e}'
        
        # Override the contents of the output directory if it already exists?
        force_override: false
        
        # Generate pdf versions of the plotted figures?
        gen_pdf: false
        
        # Generate simple latex versions of the plotted figures?
        gen_tex: true
        
        # Generate excel files for all tables
        gen_xls: false
        
        # Name of the HTML file
        html_filename: report.html
        
        # Show the mean related values in the big comparison table
        mean_in_comparison_tables: true
        
        # Show the mininmum related values in the big comparison table
        min_in_comparison_tables: false
        
        # Output directory
        out: report
        
        # Format string used to format floats as percentages
        percent_format: '{:5.2%}'
        
        # Show zoomed out (x min = 0) figures in the extended summaries?
        show_zoomed_out: false
    
    #   Reporter that produces a HTML bsaed report with lot's of graphics.
    html_misc:
        
        # Run to to use as base run for relative values in comparison table
        compare_against: 0
        
        # Properties to include in comparison table
        compared_props: [all]
        
        # Name of the HTML file
        html_filename: report.html
        
        # Output directory
        out: report
        
        # Kind of plot to draw for pair plots (see searborn.joinplot)
        pair_kind: kde
        
        # Width of the plots in centimeters
        plot_size: 8
    
    number:
        
        # Don't omit the minimum number of decimal places if insignificant?
        force_min_decimal_places: true
        
        # The maximum number of decimal places
        max_decimal_places: 2
        
        # The minimum number of shown decimal places if decimal places are shown
        min_decimal_places: 2
        
        # Omit insignificant decimal places
        omit_insignificant_decimal_places: false
        
        # Show parentheses around non significant digits? (If a std dev is given)
        parentheses: true
        
        # Mode for showing the parentheses: either d (Digits are considered significant if they don't change if the number itself changes += $sigmas * std dev) or o (digits are consideredsignificant if they are bigger than $sigmas * std dev)
        parentheses_mode: o
        
        # Show as percentages
        percentages: false
        
        # Use the exponential notation, i.e. '10e3' for 1000
        scientific_notation: false
        
        # Use si prefixes instead of 'e…'
        scientific_notation_si_prefixes: false
        
        # Number of standard deviation used for the digit significance evaluation
        sigmas: 2

run:
    
    # Append to the output file instead of overwriting by adding new run data blocks
    append: false
    
    # Disable the hyper threaded cores. Good for cpu bound programs.
    disable_hyper_threading: false
    
    # Discard all run data for the failing program on error
    discard_all_data_for_block_on_error: false
    
    # First n runs that are discarded
    discarded_runs: 1
    
    # Possible run drivers are 'exec' and 'shell'
    driver: exec
    
    # Input file with the program blocks to benchmark
    in: input.exec.yaml
    
    # Maximum time one run block should take, -1s == no timeout
    max_block_time: -1s
    
    # Maximum number of benchmarking runs
    max_runs: 50
    
    # Maximum time the whole benchmarking should take, -1s == no timeout
    max_time: -1s
    
    # Minimum number of benchmarking runs
    min_runs: 20
    
    # Output file for the benchmarking results
    out: run_output.yaml
    
    # Number of benchmarking runs that are done together
    run_block_size: 1
    
    # if != -1 sets max and min runs to it's value
    runs: -1
    
    # If not empty, recipient of a mail after the benchmarking finished.
    send_mail: ''
    
    # Print console report if log_level=info
    show_report: true
    
    # Randomize the order in which the program blocks are benchmarked.
    shuffle: true
    
    # Store the result file after each set of blocks is benchmarked
    store_often: false
    
    cpuset:
        
        # Use cpuset functionality?
        active: false
        
        # Number of cpu cores for the base (remaining part of the) system
        base_core_number: 1
        
        # 0: benchmark sequential, > 0: benchmark parallel with n instances, -1: determine n automatically
        parallel: 0
        
        # Number of cpu cores per parallel running program.
        sub_core_number: 1
    
    #   Implements a simple run driver that just executes one of the passed run_cmds
    #   in each benchmarking run.
    #   It meausures the time  using the perf stat tool (runner=perf_stat).
    #   
    #   The constructor calls the ``setup`` method.
    exec_misc:
        
        # Enable other plugins by default: none =  (enable none by default); all = cpu_governor,disable_swap,sync,stop_start,other_nice,nice,disable_aslr,disable_ht,disable_intel_turbo (enable all, might freeze your system); usable = cpu_governor,disable_swap,sync,nice,disable_aslr,disable_ht,disable_intel_turbo (like 'all' but doesn't affect other processes)
        preset: none
        
        # Pick a random command if more than one run command is passed.
        random_cmd: true
        
        # If not '' overrides the runner setting for each program block
        runner: ''
    
    exec_plugins:
        
        # Enable:   Allows the setting of the scaling governor of all cpu cores, to ensure that all use the same.
        cpu_governor_active: null
        
        # Enable:   Disable address space randomization
        disable_aslr_active: null
        
        # Enable:   Disable the L1 and L2 caches on x86 and x86-64 architectures.
        #   Uses a small custom kernel module (be sure to compile it via 'temci setup').
        #   
        #   :warning: slows program down significantly and has probably other weird consequences
        #   :warning: this is untested
        #   :warning: a linux-forum user declared: Disabling cpu caches gives you a pentium I like processor!!!
        disable_cpu_caches_active: null
        
        # Enable:   Disable hyper-threading
        disable_ht_active: null
        
        # Enable:   Disable intel turbo mode
        disable_intel_turbo_active: null
        
        # Enable:   Disables swapping on the system before the benchmarking and enables it after.
        disable_swap_active: null
        
        # Enable:   Drop page cache, directoy entries and inodes before every benchmarking run.
        drop_fs_caches_active: null
        
        # Enable:   Adds random environment variables.
        env_randomize_active: null
        
        # Possible run driver plugins are 'nice', 'env_randomize', 'preheat', 'other_nice', 'stop_start', 'sync', 'sleep', 'drop_fs_caches', 'disable_swap', 'disable_cpu_caches', 'cpu_governor', 'disable_aslr', 'disable_ht' and 'disable_intel_turbo'
        exec_active: []
        
        # Enable:   Allows the setting of the nice and ionice values of the benchmarking process.
        nice_active: null
        
        # Enable:   Allows the setting of the nice value of most other processes (as far as possible).
        other_nice_active: null
        
        # Enable:   Preheats the system with a cpu bound task
        #   (calculating the inverse of a big random matrice with numpy).
        preheat_active: null
        
        # Enable:   Sleep a given amount of time before the benchmarking begins.
        #   
        #   See Gernot Heisers Systems Benchmarking Crimes:
        #   Make sure that the system is really quiescent when starting an experiment,
        #   leave enough time to ensure all previous data is flushed out.
        sleep_active: null
        
        # Enable:   Stop almost all other processes (as far as possible).
        stop_start_active: null
        
        # Enable:   Calls ``sync`` before each program execution.
        sync_active: null
        
        #   Allows the setting of the scaling governor of all cpu cores, to ensure that all use the same.
        cpu_governor_misc:
            
            # New scaling governor for all cpus
            governor: performance
        
        #   Disable address space randomization
        disable_aslr_misc: !!map {}
        
        #   Disable the L1 and L2 caches on x86 and x86-64 architectures.
        #   Uses a small custom kernel module (be sure to compile it via 'temci setup').
        #   
        #   :warning: slows program down significantly and has probably other weird consequences
        #   :warning: this is untested
        #   :warning: a linux-forum user declared: Disabling cpu caches gives you a pentium I like processor!!!
        disable_cpu_caches_misc: !!map {}
        
        #   Disable hyper-threading
        disable_ht_misc: !!map {}
        
        #   Disable intel turbo mode
        disable_intel_turbo_misc: !!map {}
        
        #   Disables swapping on the system before the benchmarking and enables it after.
        disable_swap_misc: !!map {}
        
        #   Drop page cache, directoy entries and inodes before every benchmarking run.
        drop_fs_caches_misc:
            
            # Free dentries and inodes
            free_dentries_inodes: true
            
            # Free the page cache
            free_pagecache: true
        
        #   Adds random environment variables.
        env_randomize_misc:
            
            # Maximum length of each random key
            key_max: 4096
            
            # Maximum number of added random environment variables
            max: 4
            
            # Minimum number of added random environment variables
            min: 4
            
            # Maximum length of each random value
            var_max: 4096
        
        #   Allows the setting of the nice and ionice values of the benchmarking process.
        nice_misc:
            
            # Specify the name or number of the scheduling class to use;0 for none, 1 for realtime, 2 for best-effort, 3 for idle.
            io_nice: 1
            
            # Niceness values range from -20 (most favorable to the process) to 19 (least favorable to the process).
            nice: -15
        
        #   Allows the setting of the nice value of most other processes (as far as possible).
        other_nice_misc:
            
            # Processes with lower nice values are ignored.
            min_nice: -10
            
            # Niceness values for other processes.
            nice: 19
        
        #   Preheats the system with a cpu bound task
        #   (calculating the inverse of a big random matrice with numpy).
        preheat_misc:
            
            # Number of seconds to preheat the system with an cpu bound task
            time: 10
        
        #   Sleep a given amount of time before the benchmarking begins.
        #   
        #   See Gernot Heisers Systems Benchmarking Crimes:
        #   Make sure that the system is really quiescent when starting an experiment,
        #   leave enough time to ensure all previous data is flushed out.
        sleep_misc:
            
            # Seconds to sleep
            seconds: 10
        
        #   Stop almost all other processes (as far as possible).
        stop_start_misc:
            
            # Each process which name (lower cased) starts with one of the prefixes is not ignored. Overrides the decision based on the min_id.
            comm_prefixes: [ssh, xorg, bluetoothd]
            
            # Each process which name (lower cased) starts with one of the prefixes is ignored. It overrides the decisions based on comm_prefixes and min_id.
            comm_prefixes_ignored: [dbus, kworker]
            
            # Just output the to be stopped processes but don't actually stop them?
            dry_run: false
            
            # Processes with lower id are ignored.
            min_id: 1500
            
            # Processes with lower nice values are ignored.
            min_nice: -10
            
            # Suffixes of processes names which are stopped.
            subtree_suffixes: [dm, apache]
        
        #   Calls ``sync`` before each program execution.
        sync_misc: !!map {}
    
    #   Implements a run driver that runs the benched command a single time with redirected in- and output.
    #   It can be used to run own benchmarking commands inside a sane benchmarking environment
    #   
    #   The constructor calls the ``setup`` method.
    shell_misc:
        
        # Enable other plugins by default: none =  (enable none by default); all = cpu_governor,disable_swap,sync,stop_start,other_nice,nice,disable_aslr,disable_ht,disable_intel_turbo (enable all, might freeze your system); usable = cpu_governor,disable_swap,sync,nice,disable_aslr,disable_ht,disable_intel_turbo (like 'all' but doesn't affect other processes)
        preset: none

stats:
    
    # Properties to use for reporting and null hypothesis tests
    properties: [all]
    
    # Possible testers are 't', 'ks' and 'anderson'
    tester: t
    
    # Range of p values that allow no conclusion.
    uncertainty_range: !!python/tuple [0.05, 0.15]
    
    #   Tester that uses the Anderson statistic on 2 samples.
    anderson_misc: !!map {}
    
    #   Tester that uses the Kolmogorov-Smirnov statistic on 2 samples.
    ks_misc: !!map {}
    
    #   Tester that uses the student's t test.
    t_misc: !!map {}
```
