### ISSUE TITLE
Runners should give readable names to properties

### ISSUE THREAD

**Issue by qznc** [parttimenerd/temci#7]
For example, I have no idea what "nivcsw" from the rusage runner is. The report should explain that it counts "involuntary context switches".

**Comment by parttimenerd** [comment]
Good idea. This should be easy as the descriptions are already encoded for most runners (except spec(.py) and perf_stat). The only problem is that these descriptions have to be encoded in the benchmarking result files. Maybe like

```
- attributes:
   - …
  data:
      …
  property_descriptions:
      [property]: [description]
```

Or by just adding `runner: …` (instead of `property_descriptions`) to each result block.
The properties could than be replaced by their descriptions at result file load time (if a flag is present). 

What do you think?

**Comment by qznc** [comment]
Does it make sense to have this as child elements of attributes? The names are the same for every one. Otherwise it would make no sense to compare anything. So more like

 ```yaml
- attributes: {description: ls}
  ...
- attributes: {description: ls --color}
  ...
- property_descriptions:
      nivcsw: "involuntary context switches"
      majflt: "hard page faults"
      ...
```
